name: ci
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read
jobs:
  x86_64-linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y bash git ninja-build cmake gcc g++
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
      - name: Build
        run: sh ci/build_native.sh
